# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages
RUN npm install

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run the Node.js app when the container launches
CMD ["node", "show_results.js"]
