version: '3'

services:
  enter_data:
    build:
      context: .
      dockerfile: Dockerfile.enterdata
    ports:
      - "5000:5000"
    networks:
      - micro

  show_results:
    build:
      context: .
      dockerfile: Dockerfile.showresults
    ports:
      - "5001:5001"
    networks:
      - micro

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "5002:5002"
    networks:
      - micro

  analytics:
    build:
      context: .
      dockerfile: Dockerfile.analytics
    ports:
      - "5003:5003"
    networks:
      - micro

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: data_db
      MYSQL_USER: data_user
      MYSQL_PASSWORD: data_password
    networks:
      - micro

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - micro

networks:
  micro:
    driver: bridge